// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvghzvlkcovinfxbayhf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2Z2h6dmxrY292aW5meGJheWhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxODQyNjQsImV4cCI6MjA2NDc2MDI2NH0.gei5XmtGXDcdAF39pGr_o82PM1B_Oj_shClMo1KJj0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);